# Project: 查找学生薪资2.10（1）
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 查找学生薪资2.10（1）_private.res
OBJ      = main1.o $(RES)
LINKOBJ  = main1.o $(RES)
LIBS     = -L"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib" -L"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 查找学生薪资2.10（1）.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main1.o: main1.cpp
	$(CPP) -c main1.cpp -o main1.o $(CXXFLAGS)

查找学生薪资2.10（1）_private.res: 查找学生薪资2.10（1）_private.rc 
	$(WINDRES) -i 查找学生薪资2.10（1）_private.rc --input-format=rc -o 查找学生薪资2.10（1）_private.res -O coff 

