# Project: 素数
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 素数_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib" -L"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/x86_64-w64-mingw32/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/HBU_Course_Forth/DEV_C++/DEV-CPP/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 素数.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

素数_private.res: 素数_private.rc 
	$(WINDRES) -i 素数_private.rc --input-format=rc -o 素数_private.res -O coff 

